# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    if: false
    steps:
    - name: Checkout source code
      uses: actions/checkout@v6
    - name: install musl
      run: |
        sudo apt update \
        && sudo apt install -y --no-install-recommends musl-tools musl-dev \
        && sudo apt clean \
        && sudo rm -rf /var/lib/apt/lists/*
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        #go-version: '1.26'
        go-version-file: 'go.mod'
        # token: ${{ github.token }} 用在api调用时候,和下面作用相同
        token: ${{ secrets.GITHUB_TOKEN }}
        cache-dependency-path: 'go.sum'
    - name: Call GitHub API
      run: |
        curl -H "Authorization: Bearer ${{ github.token }}" \
        https://api.github.com/repos/${{ github.repository }}
        uname -ar
    - name: Build
      run: |
        CGO_ENABLED=1 \
        CC=musl-gcc \
        GOOS=linux \
        GOARCH=amd64 \
        go build \
        -tags "netgo osusergo" \
        -trimpath -buildvcs=false -ldflags '-s -w -linkmode external -extldflags "-static"' \
        -o dist/${{ github.event.repository.name }}-linux-amd64-musl ./src/com/ewancle
    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: ${{ github.event.repository.name }}-linux-amd64-musl
        path: dist/*

    #- name: Build
    #  run: go build -v ./...

    #- name: Test
    #  run: go test -v ./...
  docker-build:
    runs-on: ubuntu-24.04-arm
    # 在项目setting中添加的环境变量名称，才能读取对应环境下的变量（建议使用prod，test，dev来区分）
    environment: Cloudflare_R2
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # GH_TOKEN 设置这个变量，无需登录
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}

      AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_KEY }}
      AWS_ENDPOINT_URL: ${{ vars.R2_URL }}
      AWS_BUCKET: ${{ vars.R2_BUCKET }}
      AWS_DEFAULT_REGION: us-east-1
    #services:
    #  redis:
    #    image: redis
    #    ports:
    #      - 6379:6379
    container:
      image: golang:1.26-alpine # 不能运行在arm
      #credentials:
      #  username: myuser
      #  password: ${{ secrets.DOCKER_PASSWORD }}
      env:
        GO111MODULE: on
        CGO_ENABLED: 0
      #ports:
      #  - 8080
      #volumes:
      #  - my_docker_volume:/volume_mount
      #options: --cpus 2 --memory 4g 【--privileged --user root】
    steps:
      - name: Install deps
        run: |
          apk add --no-cache git
      #- uses: actions/checkout@v6 # Node.js 官方二进制只提供 glibc + x86_64 版本的 Alpine 镜像支持
      - name: Set up git
        run: |
          # 检查 git 是否存在
          git --version
          git config --global user.name "CI"
          git config --global user.email "ci@example.com"
          git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      - name: Checkout code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 直接下载代码到当前目录, 用 . 作为目标路径就可以了
          git clone --depth 1 https://github.com/${{ github.repository }} .
          git fetch --tags
          git checkout ${{ github.sha }}
          # 私有仓库
          # git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} .
          # git checkout ${{ github.sha }}
          # actions/checkout@v6 会自动处理 submodules，如果自己用 git clone，需要手动：
          # git submodule update --init --recursive
      - name: Install deps
        run: |
          apk add --no-cache curl build-base musl-dev gcc zip aws-cli groff
          uname -ar
      - name: Build
        # 对于 Alpine + CGO，只需 CC=gcc 就能正确编译静态 binary。GCC 默认会使用系统的 musl libc，因为 Alpine 是基于 musl 构建的。
        run: |
          CGO_ENABLED=1 \
          CC=gcc \
          GOOS=linux \
          GOARCH=arm64 \
          go build \
          -tags "netgo osusergo" \
          -trimpath -buildvcs=false -ldflags '-s -w -linkmode external -extldflags "-static"' \
          -o dist/${{ github.event.repository.name }}-linux-arm64-musl ./src/com/ewancle
      #- name: Upload artifact
      #  uses: actions/upload-artifact@v6
      #  with:
      #    name: ${{ github.event.repository.name }}-linux-arm64-musl
      #    path: dist/*
      - name: Install GitHub CLI
        run: |
          GH_VER=2.36.0
          ARCH=$(uname -m)
          case $ARCH in
            x86_64) ARCH=amd64 ;;
            aarch64) ARCH=arm64 ;;
          esac
          curl -L -o gh.tar.gz https://github.com/cli/cli/releases/download/v${GH_VER}/gh_${GH_VER}_linux_${ARCH}.tar.gz
          tar -xzf gh.tar.gz
          mv gh_${GH_VER}_linux_${ARCH}/bin/gh /usr/local/bin/gh
          rm -rf gh_${GH_VER}_linux_${ARCH} gh.tar.gz
          gh --version
      - name: Upload artifact
        run: |
          # echo "${GITHUB_TOKEN}" | gh auth login --with-token
          # gh run upload-artifact my-artifact.zip
          # 上传文件或目录，并指定 artifact 名称
          #gh run upload-artifact dist/${{ github.event.repository.name }}-linux-arm64-musl --name "${{ github.event.repository.name }}-linux-arm64-musl"
          # 多个文件/目录上传
          # gh run upload-artifact build/ logs/ --name "build-artifacts"
          # 上传到当前 workflow run
          RUN_ID=$(gh run list -L 1 --json databaseId -q '.[0].databaseId')
          echo "Workflow run ID: $RUN_ID"
          #chmod +x ./upload-artifact.sh
          #./upload-artifact.sh ${{ github.event.repository.name }}-linux-arm64-musl dist/${{ github.event.repository.name }}-linux-arm64-musl
          # 在 GitHub CI 中其实 **AWS CLI 已经预装**（ubuntu runner）。
          aws --version
          # aws configure CLI 正在等待交互输入进行配置
          echo "AWS_ENDPOINT_URL = $AWS_ENDPOINT_URL"
          echo "AWS_ACCESS_KEY_ID = $AWS_ACCESS_KEY_ID"
          echo "GITHUB_REPOSITORY = $GITHUB_REPOSITORY"
          # 配置信息：https://docs.aws.amazon.com/zh_cn/cli/v1/userguide/cli-configure-envvars.html
          aws configure list
          # 上传文件： 命令选项： https://docs.aws.amazon.com/zh_cn/cli/v1/userguide/cli-configure-options.html
          # aws s3 cp dist/${{ github.event.repository.name }}-linux-arm64-musl s3://$AWS_BUCKET/${{ github.event.repository.name }}-linux-arm64-musl --endpoint-url $AWS_ENDPOINT_URL
          # aws s3 ls s3://$AWS_BUCKET/test --endpoint-url $AWS_ENDPOINT_URL
          # 需要安装：groff
          # aws help
          aws s3api list-objects-v2 --bucket $AWS_BUCKET --endpoint-url $AWS_ENDPOINT_URL --region us-east-1 --debug

  matrix-build:
    runs-on: ubuntu-latest
    if: false

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          #go-version: '1.26'
          go-version-file: 'go.mod'
          token: ${{ secrets.GITHUB_TOKEN }}
          cache-dependency-path: 'go.sum'

      # -ldflags "-s -w -H windowsgui" GUI 程序不弹 console， 如果是服务：设置不要用 windowsgui。
      # CGO_ENABLED=1 1️⃣ 可以调用 C/C++ 库 【sqlite, libc, libpcap ] glibc 都建议开启
      #  当你开启 CGO_ENABLED=1 时，Go 会调用系统的 C 编译器（通常是 GCC）去编译 runtime/cgo 的汇编文件。 （所以系统也要进行交叉gcc库：apt install gcc-aarch64-linux-gnu】 或设置=0
      # 如果完全静态编译，不用 CGO → CGO_ENABLED=0
      - name: Build
        run: |
          mkdir -p dist
          if [ "${{ matrix.goos }}" = "windows" ]; then
            EXT=".exe"
          else
            EXT=""
          fi

          GOOS=${{ matrix.goos }} \
          GOARCH=${{ matrix.goarch }} \
          CGO_ENABLED=0 \
          go build -trimpath -buildvcs=false -ldflags "-s -w" \
          -o dist/${{ github.event.repository.name }}-${{ matrix.goos }}-${{ matrix.goarch }}$EXT ./src/com/ewancle

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*
