# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v6
    - name: install musl
      run: |
        sudo apt update \
        && sudo apt install -y --no-install-recommends musl-tools musl-dev \
        && sudo apt clean \
        && sudo rm -rf /var/lib/apt/lists/*
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        #go-version: '1.26'
        go-version-file: 'go.mod'
        # token: ${{ github.token }} 用在api调用时候,和下面作用相同
        token: ${{ secrets.GITHUB_TOKEN }}
        cache-dependency-path: 'go.sum'
    - name: Call GitHub API
      run: |
        curl -H "Authorization: Bearer ${{ github.token }}" \
        https://api.github.com/repos/${{ github.repository }}
        uname -ar
    - name: Build
      run: |
        CGO_ENABLED=1 \
        CC=musl-gcc \
        GOOS=linux \
        GOARCH=amd64 \
        go build \
        -tags "netgo osusergo" \
        -trimpath -buildvcs=false -ldflags '-s -w -linkmode external -extldflags "-static"' \
        -o dist/${{ github.event.repository.name }}-linux-amd64-musl ./src/com/ewancle
    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: ${{ github.event.repository.name }}-linux-amd64-musl
        path: dist/*

    #- name: Build
    #  run: go build -v ./...

    #- name: Test
    #  run: go test -v ./...
  docker-build:
    runs-on: ubuntu-24.04-arm
    #services:
    #  redis:
    #    image: redis
    #    ports:
    #      - 6379:6379
    container:
      image: golang:1.26-alpine # 不能运行在arm
      #credentials:
      #  username: myuser
      #  password: ${{ secrets.DOCKER_PASSWORD }}
      env:
        GO111MODULE: on
        CGO_ENABLED: 0
      #ports:
      #  - 8080
      #volumes:
      #  - my_docker_volume:/volume_mount
      #options: --cpus 2 --memory 4g 【--privileged --user root】
    steps:
      - name: Install deps
        run: |
          apk add --no-cache git
      #- uses: actions/checkout@v6 # Node.js 官方二进制只提供 glibc + x86_64 版本的 Alpine 镜像支持
      - name: Set up git
        run: |
          # 检查 git 是否存在
          git --version
          git config --global user.name "CI"
          git config --global user.email "ci@example.com"
      - name: Checkout code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # ，直接下载代码到当前目录, 用 . 作为目标路径就可以了
          git clone --depth 1 https://github.com/${{ github.repository }} .
          git fetch --tags
          git checkout ${{ github.sha }}
          # 私有仓库
          # git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} .
          # git checkout ${{ github.sha }}
          # actions/checkout@v6 会自动处理 submodules，如果自己用 git clone，需要手动：
          # git submodule update --init --recursive
      - name: Install deps
        run: |
          apk add --no-cache git build-base musl-dev
          uname -ar
      - name: Build
        run: |
          CGO_ENABLED=1 \
          CC=musl-gcc \
          GOOS=linux \
          GOARCH=arm64 \
          go build \
          -tags "netgo osusergo" \
          -trimpath -buildvcs=false -ldflags '-s -w -linkmode external -extldflags "-static"' \
          -o dist/${{ github.event.repository.name }}-linux-arm64-musl ./src/com/ewancle
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ github.event.repository.name }}-linux-arm64-musl
          path: dist/*

  matrix-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          #go-version: '1.26'
          go-version-file: 'go.mod'
          token: ${{ secrets.GITHUB_TOKEN }}
          cache-dependency-path: 'go.sum'

      # -ldflags "-s -w -H windowsgui" GUI 程序不弹 console， 如果是服务：设置不要用 windowsgui。
      # CGO_ENABLED=1 1️⃣ 可以调用 C/C++ 库 【sqlite, libc, libpcap ] glibc 都建议开启
      #  当你开启 CGO_ENABLED=1 时，Go 会调用系统的 C 编译器（通常是 GCC）去编译 runtime/cgo 的汇编文件。 （所以系统也要进行交叉gcc库：apt install gcc-aarch64-linux-gnu】 或设置=0
      - name: Build
        run: |
          mkdir -p dist
          if [ "${{ matrix.goos }}" = "windows" ]; then
            EXT=".exe"
          else
            EXT=""
          fi

          GOOS=${{ matrix.goos }} \
          GOARCH=${{ matrix.goarch }} \
          CGO_ENABLED=0 \
          go build -trimpath -buildvcs=false -ldflags "-s -w" \
          -o dist/${{ github.event.repository.name }}-${{ matrix.goos }}-${{ matrix.goarch }}$EXT ./src/com/ewancle

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*
